apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mcp-observability-alerts
  labels:
    prometheus: mcp
    role: alert-rules
spec:
  groups:
    - name: mcp-observability.rules
      rules:
        - alert: HighRequestLatency
          expr: histogram_quantile(0.95, sum by (le)(rate(request_latency_seconds_bucket[5m]))) > 0.15
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High p95 request latency detected"
            description: "p95 latency is above 150 ms for the last 5 minutes."
        - alert: HighErrorRate
          expr: sum(rate(http_server_errors_total[5m])) / sum(rate(http_server_requests_total[5m])) > 0.05
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High HTTP error rate detected"
            description: "Error rate exceeded 5 % for the last 5 minutes." 