{
 "title": "Loki Error",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "All alerts", "type": "alertlist", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "account-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"account-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "advert-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"advert-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "auth-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"auth-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "banking-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"banking-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "control-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"control-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "bonus-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"bonus-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "cashier-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"cashier-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "casino-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"casino-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "casino-winners-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"casino-winners-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "config-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"config-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "report-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"report-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "crypto-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"crypto-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "locale-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"locale-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "messaging-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"messaging-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "payment-fm-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"payment-fm-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "referral-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"referral-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "users-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"users-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "search-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"search-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "site-messaging-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"site-messaging-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "tickets-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"tickets-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "tickets-control-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"tickets-control-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "translation-api",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"translation-api\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "mts-client",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"mts-client\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "feedlottery",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"feedlottery\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "feedsport",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"feedsport\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "feedvirtual",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(({release=\"feedvirtual\", container=\"main\"} |~ \"level\\\":\\\"error|ERROR\")[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}