{{- if .Values.mcpServer.env.MCP_TOKEN }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-obs.fullname" . }}-mcp-token
  labels:
    {{- include "mcp-obs.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
type: Opaque
stringData:
  token: {{ .Values.mcpServer.env.MCP_TOKEN | quote }}
{{- end }}
