apiVersion: v2
name: mcp-obs
description: "Observability stack – MCP server plus Grafana, Loki, Prometheus, Tempo, and OpenTelemetry Collector"

type: application
version: 0.1.0
appVersion: "0.1.0"

# Umbrella chart: leverage upstream community charts

dependencies:
  - name: grafana
    version: "6.*"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled

  - name: loki
    version: "5.*"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled

  - name: prometheus
    version: "19.*"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled

  - name: tempo
    version: "1.*"
    repository: "https://grafana.github.io/helm-charts"
    condition: tempo.enabled

  - name: opentelemetry-collector
    version: "0.*"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: otelCollector.enabled 