# Default values for mcp-obs umbrella chart.

# Global persistence toggle – override per sub-chart below
persistence:
  enabled: false

# MCP Server image settings
mcpServer:
  image:
    repository: "ghcr.io/your-org/mcp-server"
    tag: "latest"
  # Enable PVC for the server (e.g., SQLite, logs)
  persistence:
    enabled: false
    size: 1Gi

# Upstream charts enablement flags – default all true
loki:
  enabled: true
  loki:
    persistence:
      enabled: false
      size: 5Gi

grafana:
  enabled: true
  persistence:
    enabled: false
    size: 1Gi

prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: false
      size: 5Gi

tempo:
  enabled: true
  persistence:
    enabled: false
    size: 5Gi

otelCollector:
  enabled: true
  mode: deployment
  presets:
    kubernetesAttributes: true
    kubernetesClusterReceiver: true 