# Default values for mcp-obs umbrella chart.

# Global persistence toggle – convenience flag you may reference in overrides;
# this chart does NOT automatically propagate the value to sub-charts. Use
# `helm install mcp-obs -f my-values.yaml` and set individual sub-chart
# persistence flags as desired, or leverage `--set loki.persistence.enabled=true` etc.
persistence:
  enabled: false

# MCP Server image settings
mcpServer:
  image:
    repository: "ghcr.io/your-org/mcp-server"
    tag: "latest"
  # Enable PVC for the server (e.g., SQLite, logs)
  persistence:
    enabled: false
    size: 1Gi
  # Environment variables injected into the container
  env:
    MCP_TOKEN: ""

# Upstream charts enablement flags – default all true
loki:
  enabled: true
  persistence:
    enabled: false   # If true, creates PVC via Loki chart
    size: 5Gi
  loki:
    storage:
      type: filesystem  # avoids object storage nil errors in strict lint
      bucketNames:
        chunks: ""
        ruler: ""
        admin: ""

grafana:
  enabled: true
  persistence:
    enabled: false   # Set to true for PVC backing Grafana data dir
    size: 1Gi

prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: false
      size: 5Gi

tempo:
  enabled: true
  persistence:
    enabled: false
    size: 5Gi

otelCollector:
  enabled: true
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      filelog:
        include:
          - /var/log/app/**/*.log
        start_at: beginning

    processors:
      batch:

    exporters:
      loki:
        endpoint: http://loki:3100/loki/api/v1/push
      otlp/tempo:
        endpoint: tempo:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp/tempo]
        logs:
          receivers: [filelog]
          exporters: [loki]
  presets:
    kubernetesAttributes: true
    kubernetesClusterReceiver: true

# TLS / cert-manager settings for mcp-server
tls:
  enabled: true            # When true, chart provisions Certificate & Issuer and mounts secret
  secretName: mcp-server-tls
  issuer:
    create: true           # Create a self-signed Issuer when true
    name: mcp-selfsigned-issuer
    kind: Issuer           # "Issuer" or "ClusterIssuer"

# Ingress settings for MCP Server
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: mcp.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []  # - secretName: mcp-server-tls

# Dashboards ConfigMap
dashboards:
  enabled: true
  # If true, bundles the pre-built Grafana dashboards JSON into a ConfigMap
  # and mounts it under /grafana/dashboards in the Grafana deployment (sub-chart logic)
  label: grafana_dashboard
