name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      MCP_TOKEN: testtoken
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Lint
        run: |
          poetry run black --check .
          poetry run isort --check-only .
          poetry run mypy app

      - name: Test with coverage
        run: |
          poetry run pytest --cov=app --cov=app --cov-fail-under=90 -q

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: .coverage 