name: Package Helm Chart

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'
      - '.github/workflows/helm-package.yml'
  workflow_dispatch:

jobs:
  helm-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.3

      - name: Build dependencies
        run: helm dependency update charts/mcp-obs

      - name: Package chart
        run: |
          mkdir -p packaged
          helm package charts/mcp-obs --destination packaged

      - name: Upload packaged chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: packaged/*.tgz 