name: Integration Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: false
        default: "local"

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Run integration tests
        run: |
          poetry run pytest -m "not unit" --cov=app --cov-fail-under=69 -q

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: .pytest_cache 